### ISSUE TITLE
Window State v2

### ISSUE THREAD

**Issue by WesSouza** [WesSouza/wes.dev#36]
Improve the windowing system:

- [x] Wrap opening window position around screen constraints
- [x] Position first notepad proportionally to screen size
- [x] Fix issue where focusing on a window moves it
- [x] Fix issue when clicking a button on an unfocused window doesn't trigger its action
- [x] Fix lack of clipping on mobile allowing screen to be zoomed out when windows overflow
- [x] Fix janky minimizing and restoring behavior on taskbar

**Comment by v42** [comment]
when you focus an unfocused window by clicking a button it should trigger the button action too, no?
