### ISSUE TITLE
Bug: open and closing windows vs window positioning

### ISSUE THREAD

**Issue by v42** [WesSouza/wes.dev#45]
if you close some windows and then open new ones, you get some weird positioning behaviours

**Comment by WesSouza** [comment]
@v42 Windows seems to always open the next window based on the position it opened the previous window, which I reimplemented here.

**Comment by v42** [comment]
I don't exactly remember what happens on these cases, but if you close all the windows and try to open new ones then maybe window positioning should reset, no?

also, if you open too many windows then the new ones goes out of boundaries in Y axis

**Comment by WesSouza** [comment]
I recommend you play around with a VM or [felixrieseberg/windows95](https://github.com/felixrieseberg/windows95), it is the correct behavior.

Window out of bounds feature is tracked on #36.
